[package]
name = "snek"
version = "0.1.0"
authors = ["Thomas Huber <me@tohuber.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
nalgebra = "0.18.0"
rand = "0.7.2"
